import { jsPDF } from 'jspdf';
import { Trip } from '@/types';
import { calculateDistance, formatDistance } from './geo';

export function exportTripToPDF(trip: Trip) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number, isBold = false, color = '#000000') => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color);
    
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.5) + 2;
  };

  // Helper to check page break
  const checkPageBreak = (neededSpace: number) => {
    if (y + neededSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  addText(trip.name, 24, true);
  y += 5;

  // Trip stats
  let totalDistance = 0;
  for (let i = 0; i < trip.cities.length - 1; i++) {
    totalDistance += calculateDistance(
      trip.cities[i].lat, trip.cities[i].lng,
      trip.cities[i + 1].lat, trip.cities[i + 1].lng
    );
  }
  const firstDate = trip.cities[0]?.arriveDate;
  const lastCity = trip.cities[trip.cities.length - 1];
  const lastDate = lastCity?.departDate || lastCity?.arriveDate;
  const days = firstDate && lastDate 
    ? Math.ceil((new Date(lastDate).getTime() - new Date(firstDate).getTime()) / (1000 * 60 * 60 * 24)) + 1
    : null;

  let stats = `${trip.cities.length} destination${trip.cities.length !== 1 ? 's' : ''}`;
  if (totalDistance > 0) stats += ` | ${formatDistance(totalDistance)} total`;
  if (days) stats += ` | ${days} day${days !== 1 ? 's' : ''}`;
  
  addText(stats, 11, false, '#666666');
  y += 10;

  // Itinerary section
  addText('ITINERARY', 14, true, '#333333');
  y += 5;

  trip.cities.forEach((city, index) => {
    checkPageBreak(60);
    
    // City name
    addText(`${index + 1}. ${city.name}, ${city.country}`, 12, true);
    
    // Dates
    const formatDate = (date: string) => {
      return new Date(date).toLocaleDateString('en-US', {
        weekday: 'short',
        month: 'short',
        day: 'numeric',
        year: 'numeric',
      });
    };
    
    let dateStr = formatDate(city.arriveDate);
    if (city.departDate) {
      dateStr += ` to ${formatDate(city.departDate)}`;
    }
    addText(dateStr, 10, false, '#666666');

    // Notes
    if (city.notes) {
      addText(`Notes: ${city.notes}`, 10, false, '#444444');
    }

    // Activities
    if (city.activities && city.activities.length > 0) {
      y += 2;
      addText('Activities:', 10, true, '#555555');
      city.activities.forEach((activity) => {
        checkPageBreak(20);
        let actText = `• ${activity.name}`;
        if (activity.date) {
          actText += ` (${formatDate(activity.date)})`;
        }
        addText(actText, 9, false, '#444444');
        if (activity.description) {
          addText(`  ${activity.description}`, 8, false, '#666666');
        }
      });
    }

    y += 8;
  });

  // Travelers section
  checkPageBreak(40);
  y += 5;
  addText('TRAVELERS', 14, true, '#333333');
  y += 5;

  trip.members.forEach((member) => {
    checkPageBreak(15);
    let memberText = member.user.name;
    if (member.role === 'creator') {
      memberText += ' (Organizer)';
    }
    addText(`• ${memberText}`, 10, false);
  });

  // Footer
  y += 15;
  checkPageBreak(20);
  doc.setFontSize(8);
  doc.setTextColor('#999999');
  doc.text(`Generated by TripLink on ${new Date().toLocaleDateString()}`, margin, y);

  // Save
  const filename = `${trip.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_itinerary.pdf`;
  doc.save(filename);
}
